// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRent.Infrastructure.Persistence;

#nullable disable

namespace SmartRent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Amenity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_amenities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_amenities_name");

                    b.ToTable("amenities", null, t =>
                        {
                            t.HasCheckConstraint("ck_amenities_scope", "scope IN ('KhuTro', 'Phong')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<int>("BillingCycleDay")
                        .HasColumnType("integer")
                        .HasColumnName("billing_cycle_day");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<DateTimeOffset?>("DepositReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deposit_received_at");

                    b.Property<string>("DepositReceivedMethod")
                        .HasColumnType("text")
                        .HasColumnName("deposit_received_method");

                    b.Property<decimal>("ElectricityUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("electricity_unit_price");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly?>("ExpectedMoveOutDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_move_out_date");

                    b.Property<DateTimeOffset?>("MoveOutNoticeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("move_out_notice_at");

                    b.Property<int>("PaymentDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_due_days");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("rent_price");

                    b.Property<long?>("RentalRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("rental_request_id");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TenantConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tenant_confirmed_at");

                    b.Property<long>("TenantUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_user_id");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.Property<decimal>("WaterUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("water_unit_price");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("RentalRequestId")
                        .HasDatabaseName("ix_contracts_rental_request_id");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasDatabaseName("ux_contracts_room_dang_chiem_dung")
                        .HasFilter("status IN ('DangHieuLuc', 'SapHetHan', 'DangThanhLy')");

                    b.HasIndex("TenantUserId")
                        .HasDatabaseName("ix_contracts_tenant_user_id");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_contracts_status", "status IN ('Nhap', 'ChoNguoiThueXacNhan', 'ChoNhanCoc', 'DangHieuLuc', 'SapHetHan', 'DangThanhLy', 'DaThanhLy', 'DaHuy')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.ContractOccupant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_contract_occupants");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_occupants_contract_id");

                    b.ToTable("contract_occupants", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.ContractServiceFee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_contract_service_fees");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_service_fees_contract_id");

                    b.ToTable("contract_service_fees", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdjustedInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("adjusted_invoice_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<decimal>("CurrentElectricityIndex")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("current_electricity_index");

                    b.Property<decimal>("CurrentWaterIndex")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("current_water_index");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ElectricityAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("electricity_amount");

                    b.Property<string>("ElectricityMeterPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("electricity_meter_photo_url");

                    b.Property<decimal>("ElectricityUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("electricity_unit_price");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<decimal>("PreviousElectricityIndex")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("previous_electricity_index");

                    b.Property<decimal>("PreviousWaterIndex")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("previous_water_index");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("rent_amount");

                    b.Property<decimal>("ServiceFeeAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("service_fee_amount");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<decimal>("WaterAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("water_amount");

                    b.Property<string>("WaterMeterPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("water_meter_photo_url");

                    b.Property<decimal>("WaterUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("water_unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("AdjustedInvoiceId")
                        .HasDatabaseName("ix_invoices_adjusted_invoice_id");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("ix_invoices_status_due_date");

                    b.HasIndex("ContractId", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_contract_ky_dinh_ky")
                        .HasFilter("type = 'DinhKy'");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_chi_so_dien", "current_electricity_index >= previous_electricity_index");

                            t.HasCheckConstraint("ck_invoices_chi_so_nuoc", "current_water_index >= previous_water_index");

                            t.HasCheckConstraint("ck_invoices_status", "status IN ('Nhap', 'ChuaThanhToan', 'ChoXacNhan', 'ThanhToanMotPhan', 'QuaHan', 'DaThanhToan', 'DaHuy')");

                            t.HasCheckConstraint("ck_invoices_type", "type IN ('DinhKy', 'ThanhLy', 'DieuChinh')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("evidence_url");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_invoice_lines");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.ToTable("invoice_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_lines_category", "category IN ('CongNoKyTruoc', 'BoiThuongHuHong', 'PhiPhat', 'KhauTruTienCoc', 'DieuChinhKhac')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.LandlordApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IdCardBackUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_card_back_url");

                    b.Property<string>("IdCardFrontUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_card_front_url");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_card_number");

                    b.Property<string>("OwnershipDocumentUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_document_url");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_landlord_applications");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_landlord_applications_reviewed_by_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_landlord_applications_user_id_status");

                    b.ToTable("landlord_applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_landlord_applications_status", "status IN ('ChoDuyet', 'DaDuyet', 'TuChoi', 'DaThuHoi')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("RelatedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId", "IsRead")
                        .HasDatabaseName("ix_notifications_recipient_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PaymentReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("confirmed_amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<long?>("ConfirmedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<string>("ProofImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proof_image_url");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<decimal>("ReportedAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("reported_amount");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payment_reports");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("ix_payment_reports_confirmed_by_user_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payment_reports_invoice_id");

                    b.ToTable("payment_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_reports_status", "status IN ('ChoXacNhan', 'DaXacNhan', 'TuChoiXacNhan')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<long>("LandlordUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("landlord_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Ward")
                        .HasColumnType("text")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("LandlordUserId")
                        .HasDatabaseName("ix_properties_landlord_user_id");

                    b.HasIndex("City", "District", "Ward")
                        .HasDatabaseName("ix_properties_city_district_ward");

                    b.ToTable("properties", null, t =>
                        {
                            t.HasCheckConstraint("ck_properties_status", "status IN ('DangKhaiThac', 'LuuTru')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PropertyAmenity", b =>
                {
                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<long>("AmenityId")
                        .HasColumnType("bigint")
                        .HasColumnName("amenity_id");

                    b.HasKey("PropertyId", "AmenityId")
                        .HasName("pk_property_amenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("ix_property_amenities_amenity_id");

                    b.ToTable("property_amenities", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_property_images");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_property_images_property_id");

                    b.ToTable("property_images", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RentalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ExpectedMoveInDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_move_in_date");

                    b.Property<int>("ExpectedOccupants")
                        .HasColumnType("integer")
                        .HasColumnName("expected_occupants");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("TenantUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_user_id");

                    b.HasKey("Id")
                        .HasName("pk_rental_requests");

                    b.HasIndex("TenantUserId")
                        .HasDatabaseName("ix_rental_requests_tenant_user_id");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("ix_rental_requests_room_id_status");

                    b.ToTable("rental_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_rental_requests_status", "status IN ('ChoDuyet', 'DaDuyet', 'DaLapHopDong', 'TuChoi', 'DaHuy', 'HetHan')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("area");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("ElectricityUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("electricity_unit_price");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("integer")
                        .HasColumnName("max_occupants");

                    b.Property<string>("OccupancyStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occupancy_status");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("rent_price");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility_status");

                    b.Property<decimal>("WaterUnitPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("water_unit_price");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("Area")
                        .HasDatabaseName("ix_rooms_area");

                    b.HasIndex("MaxOccupants")
                        .HasDatabaseName("ix_rooms_max_occupants");

                    b.HasIndex("RentPrice")
                        .HasDatabaseName("ix_rooms_rent_price");

                    b.HasIndex("OccupancyStatus", "VisibilityStatus")
                        .HasDatabaseName("ix_rooms_occupancy_status_visibility_status");

                    b.HasIndex("PropertyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_property_id_code");

                    b.ToTable("rooms", null, t =>
                        {
                            t.HasCheckConstraint("ck_rooms_occupancy_status", "occupancy_status IN ('Trong', 'DangGiuCho', 'DangThue', 'BaoTri', 'LuuTru')");

                            t.HasCheckConstraint("ck_rooms_visibility_status", "visibility_status IN ('DangHienThi', 'DaAnBoiChuTro', 'DaAnBoiAdmin')");
                        });
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomAmenity", b =>
                {
                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<long>("AmenityId")
                        .HasColumnType("bigint")
                        .HasColumnName("amenity_id");

                    b.HasKey("RoomId", "AmenityId")
                        .HasName("pk_room_amenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("ix_room_amenities_amenity_id");

                    b.ToTable("room_amenities", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_room_images");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_images_room_id");

                    b.ToTable("room_images", (string)null);
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomServiceFee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_room_service_fees");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_service_fees_room_id");

                    b.ToTable("room_service_fees", (string)null);
                });

            modelBuilder.Entity("SmartRent.Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SmartRent.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("LockReason")
                        .HasColumnType("text")
                        .HasColumnName("lock_reason");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Contract", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.RentalRequest", "RentalRequest")
                        .WithMany()
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_rental_requests_rental_request_id");

                    b.HasOne("SmartRent.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_rooms_room_id");

                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_users_tenant_user_id");

                    b.Navigation("RentalRequest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.ContractOccupant", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Contract", "Contract")
                        .WithMany("Occupants")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_occupants_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.ContractServiceFee", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Contract", "Contract")
                        .WithMany("ServiceFees")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_service_fees_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Invoice", "AdjustedInvoice")
                        .WithMany()
                        .HasForeignKey("AdjustedInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoices_invoices_adjusted_invoice_id");

                    b.HasOne("SmartRent.Domain.Entities.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_contracts_contract_id");

                    b.Navigation("AdjustedInvoice");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_lines_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.LandlordApplication", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_landlord_applications_users_reviewed_by_user_id");

                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_landlord_applications_users_user_id");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PaymentReport", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_reports_users_confirmed_by_user_id");

                    b.HasOne("SmartRent.Domain.Entities.Invoice", "Invoice")
                        .WithMany("PaymentReports")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_reports_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Property", b =>
                {
                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("LandlordUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_properties_users_landlord_user_id");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PropertyAmenity", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_property_amenities_amenities_amenity_id");

                    b.HasOne("SmartRent.Domain.Entities.Property", "Property")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_amenities_properties_property_id");

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_images_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RentalRequest", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rental_requests_rooms_room_id");

                    b.HasOne("SmartRent.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rental_requests_users_tenant_user_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Room", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_properties_property_id");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomAmenity", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_amenities_amenities_amenity_id");

                    b.HasOne("SmartRent.Domain.Entities.Room", "Room")
                        .WithMany("Amenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_amenities_rooms_room_id");

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomImage", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_images_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.RoomServiceFee", b =>
                {
                    b.HasOne("SmartRent.Domain.Entities.Room", "Room")
                        .WithMany("ServiceFees")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_service_fees_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Occupants");

                    b.Navigation("ServiceFees");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PaymentReports");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartRent.Domain.Entities.Room", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("ServiceFees");
                });
#pragma warning restore 612, 618
        }
    }
}
